### ISSUE TITLE
"Non-unqiue Mixin" crash at launch

### ISSUE THREAD

**Issue by Scarlaid** [KrLite/Warp-Zone#3]
`[09:12:04] [main/ERROR]: Unable to register injection point com.ishland.earlyloadingscreen.EarlyLaunch for earlyloadingscreen.mixins.json, class is not assignable to class org.spongepowered.asm.mixin.injection.InjectionPoint
Exception caught from launcher
java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods modid and warp-zone
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)`

While having both Warp Zone and EarlyLoadingScreen, it refuses to launch and throw this error
Without Warp Zone the game launchs fine

I have tried without ELS, and it would just throw a vanilla crash
`Exception caught from launcher
java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods modid and warp-zone
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)`
	
Currently on 1.19.4, Fabric Loader

**Comment by KrLite** [comment]
It's a really stupid one which I forgot to change the mixin file name from `modid.mixins.json` to something else.
Fixed in [`v1.2.2`](https://modrinth.com/mod/warp-zone/version/1.19.4-v1.2.2)
